######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 24 04:19:49 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Screen.h
SOURCES += main.cpp Screen.cpp
